# Generated by Django 5.0.6 on 2024-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('ro', 'Domestic RO Service'), ('softener', 'Commercial & Industrial Ro Service'), ('waste', 'Water Softener & Conditioner Service'), ('pool', 'Swimming Pool Filtration Service'), ('heat', 'Heat & Pressure Pump Service'), ('solar', 'Alkaline Water Service'), ('stp', 'AMC Service')], max_length=20)),
            ],
        ),
    ]
