# Generated by Django 5.0.6 on 2024-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('product', models.CharField(choices=[('domestic', 'Domestic RO'), ('commercial', 'Commercial RO'), ('commercial1', 'Commercial RO Plant Capacity 100 LPH'), ('commercial2', 'Commercial RO Plant Capacity 200 LPH'), ('commercial3', 'Commercial RO Plant Capacity 250 LPH'), ('industrial', 'Industrial RO'), ('industrial1', 'Industrial RO Plant Capacity upto 500 LPH'), ('industrial2', 'Industrial RO Plant Capacity upto 1000 LPH'), ('industrial3', 'Industrial RO Plant Capacity upto 6000 LPH'), ('watersoft', 'Water Softner'), ('waterconditioner', 'Water Conditioner'), ('pressure', 'Pressure Pump'), ('pool', 'Swimming Pool Filtration Equipments'), ('sewage', 'Sewage Treatment'), ('rainwater', 'Rain Water Harvesting'), ('heatpump', 'Heat Pump')], max_length=50)),
            ],
        ),
    ]
